### ISSUE TITLE
Breaks w/ choosenim 

### ISSUE THREAD

**Issue by zacharycarter** [Araq/nawabs#1]
Not sure if there is any desire or way to get nawabs to work with choosenim (since it uses nimble) but I've noticed on OSX, the two are not compatible. I figured I'd create an issue regarding this - but if it's not a feature that's worth considering, please feel free to chose this.

**Comment by Araq** [comment]
What do you mean, it "breaks" choosenim?

**Comment by zacharycarter** [comment]
Nevermind...
